### ISSUE TITLE
Manifest references omniboard.html, which is not included

### ISSUE THREAD

**Issue by zheaton** [jyruzicka/omniboard#1]
I tried checking out and building this project, but the gem Manifest requires `omniboard.html`, which is not included in the git repository. This causes a build failure when executing `gem build omniboard.gemspec`:

```
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["omniboard.html"] are not files
```

**Comment by jyruzicka** [comment]
And no more! Let's hope every issue is as easy to fix as this one.
