### ISSUE TITLE
OF 2.6.1 (v109.3.6 r266443) database update appears to break omniboard

### ISSUE THREAD

**Issue by tvanyo** [jyruzicka/omniboard#12]
I just got an update today (1 Aug 2016) for OF today that is using a new database file format. This appears, unsurprisingly, to break omniboard functionality.

I see you've been active in the last couple of days on the project, so hopefully there is a reasonably easy fix on your end.

**Comment by Kondamon** [comment]
I cannot confirm this issue. For me omniboard is still working. Which error message do you get?
Do you use omniboard 1.0.1? Have you already tried a reset of omniboard?

**Comment by jyruzicka** [comment]
Nope! :D Well, not yet, anyway.

The plan is to start looking at the new OF database format when I get time, but of course OmniFocus decided to release their new format right when I was packing to move countries. If I'm lucky, all it'll take is a couple of extra lines in the `rubyfocus` parser class. If I'm not, I'll have to do the decryption by hand within the library itself.

But yes, I'm aware of the issue and will be working on it as soon as possible.

**Comment by Kondamon** [comment]
Perhaps this can help a bit:

https://github.com/omnigroup/OmniGroup/tree/master/Frameworks/OmniFileStore

**Comment by jyruzicka** [comment]
Hey guys! Omnigroup's encryption (which is the major change to their database format) is only applied on the server end, and as of right now Omniboard only uses the local copy of the database. So good news: I don't have to work out how to do AESWRAP.

Omnigroup also added a couple of minor changes to their database format in the 2.6.1 release, and I've updated rubyfocus to deal with this. Hopefully this will fix any problems people are having.
