### ISSUE TITLE
omniboard --reset

### ISSUE THREAD

**Issue by Magnus-Hultin** [jyruzicka/omniboard#15]
Hi!
I have issues with the 1.0.1-release. 
The omniboard --reset does not work;
Please advice

`Magnuss-MacBook-Pro:omniboard magnus$ omniboard --reset
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:327:in `parse': no time information in "" (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:35:in `block in apply_xml'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/conditional_exec.rb:4:in `[]'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/conditional_exec.rb:4:in `conditional_set'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:35:in `apply_xml'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/item.rb:18:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:23:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/parser.rb:18:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/parser.rb:18:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:83:in `block in apply_xml'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:82:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:82:in `apply_xml'
	from /Library/Ruby/Gems/2.0.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:39:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/omniboard-1.0.1/lib/omniboard/omniboard.rb:107:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/omniboard-1.0.1/lib/omniboard/omniboard.rb:107:in `create_document'
	from /Library/Ruby/Gems/2.0.0/gems/omniboard-1.0.1/bin/omniboard:25:in `<top (required)>'
	from /usr/local/bin/omniboard:23:in `load'
	from /usr/local/bin/omniboard:23:in `<main>'
Magnuss-MacBook-Pro:omniboard magnus$ 
`

**Comment by jyruzicka** [comment]
Hi Magnus! This should hopefully have been fixed in the latest release of rubyfocus (released about two minutes prior to my posting this). Does upgrading rubyfocus (via `gem update && gem clean`) fix this issue?

**Comment by Magnus-Hultin** [comment]
Thanks!
Now it works perfectly:-)
/Magnus

4 sep. 2016 kl. 06:19 skrev Jan-Yves Ruzicka <notifications@github.com>:

Hi Magnus! This should hopefully have been fixed in the latest release of rubyfocus (released about two minutes prior to my posting this). Does upgrading rubyfocus (via gem update && gem clean) fix this issue?

**Comment by jyruzicka** [comment]
👍
