### ISSUE TITLE
HISTORY.md are not files

### ISSUE THREAD

**Issue by Edu4rdR** [jyruzicka/omniboard#16]
Hello, 

I'm trying to install your application following the instructions and it gives me this error: 
while executing gem ... (Gem::InvalidSpecificationException)
    ["HISTORY.md"] are not files

Do you have any idea of why?
I don't know any ruby at all. I'm just trying to get your Omnifocus Kansan working. I think it is a great idea. 

Cheers,
Eduard

**Comment by jyruzicka** [comment]
> Do you have any idea of why?

Because I'm a bad programmer, probably. Just updated `Manifest`, which was probably causing this error. If you delete, re-clone, and install, this should hopefully be fixed?

**Comment by jyruzicka** [comment]
I'm assuming this has fixed the problem - if you're still getting issues, feel free to re-open the ticket.
