### ISSUE TITLE
No folder names

### ISSUE THREAD

**Issue by mrmen** [jyruzicka/omniboard#21]
I can't sort my projects by folders : I have only "Active" and "Top Level".

I modified config.rb to have some info with 
```
Omniboard::Column.config do
    group_by do |p|
	  if p.ancestry == []
     		"Pas de parent"
          else
		puts p.ancestry.last.name
		""
	  end
    end
end
```
The content of p.ancestry.last.name is empty.

Actually, I can only see few projects on the kanban… most of them are missing.

I absolutely don't know Ruby, so I don' t know what could help more. I can give pictures to illustrate.

**Comment by kvndrsslr** [comment]
I had similar problems, most probably pertaining to an older database version.
For me, the following steps succeeded:

* Make backup of local database.
* Delete local database in ~/Library/Application Support/OmniFocus/
* Reopen OF
* Create new DB (dont sync)
* Open backup
* Copy projects over
* Set up sync and replace sync DB

However, using this method I was not able to retain my custom perspectives.
As I want to start from scratch with OmniFocus after having read a book about it, that didn't bother me much.

**Comment by jyruzicka** [comment]
Hi @mrmen! My guess is that you've got an issue in one of two places - either when you export data from OmniFocus, or when OmniBoard imports and formats that data.

The first thing OmniBoard does, is export everything it needs from OmniFocus' database. By default, it stores this in `~/.omniboard/db.yaml`. If you open this file in a text editor, you'll be able to see which items (contexts, projects, tasks, etc.) OmniBoard has exported (I recommend searching for project names to find specific projects in the file). Importantly, each project should have a `container_id` property, which OmniBoard uses to work out the parent folder of the project.

If you see a project/`container_id` property in `db.yaml`, and it doesn't show up on your board, it suggests that your column config isn't letting the right projects through (or perhaps OmniBoard is choking on something). If you don't see the expected projects in your `db.yaml` file at all, it suggests that perhaps something's wrong with the data import process.

Let me know what you find!

**Comment by mrmen** [comment]
Hi guys.

@jyruzicka I made some search inside db.yam and some of my projects or folders are not present.
If I'm right, it's rubyfocus who extract data into db.yaml. Playing with it show me that some of my tasks are not present in the extract.

So at the moment, I think it's an import issue. If you want I can send you a copy of my db.

**Comment by jyruzicka** [comment]
@mrmen I think I know what the issue was regarding format: sometimes RubyFocus gets confused by OmniFocus' versioning system for projects and folders. I know it's a bug, and I've meant to get back into the code and fix it for about a year now.

The display thing, though, is super-weird, and it definitely shouldn't be doing that.

If you could send me a copy of your `yaml` file, I can see if I can reproduce it on my end and work out what's happening.

**Comment by mrmen** [comment]
I was on vacation, sorry for the delay.
Actually I just ran omniboard -r -o out.html few minutes ago and everything is now OK.

I haven't modified anything in my config so let's say it's a OmniFocus magic.

I have a backup of my OmniFocus if you want.

**Comment by jyruzicka** [comment]
No problem. I suspect we wouldn't learn much from the yaml file, so let's chalk it up to magic and hope it doesn't recur.

(If it does, feel free to open a new issue.)
