### ISSUE TITLE
Issue with example code...

### ISSUE THREAD

**Issue by TurboTodd2k** [jyruzicka/omniboard#24]
I tried using your example code for grouping tasks by due date, it the code as shown throws an error though, terminal output follows...

username/.omniboard/columns/duesoon.rb:2:in `block (2 levels) in <top (required)>': undefined method `due?' for #<Rubyfocus::Project:0x00007fdb59224b38> (NoMethodError)
Did you mean?  due
               due=
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/column.rb:95:in `block in add'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rubyfocus-0.5.12/lib/rubyfocus/includes/searchable.rb:34:in `select'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rubyfocus-0.5.12/lib/rubyfocus/includes/searchable.rb:34:in `select'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/column.rb:95:in `add'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:32:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:31:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:31:in `<top (required)>'
	from /usr/local/bin/omniboard:23:in `load'
	from /usr/local/bin/omniboard:23:in `<main>'

This is using the following code...
Omniboard::Column.new "Due soon" do
	conditions{ |p| p.active? && !p.deferred? && p.due? }
	group_by{ |p| p.due.to_date - Date.today }
end

Any thoughts, not a programmer so imagine I'm making a simple mistake.

**Comment by jyruzicka** [comment]
Hi @TurboTodd2k,

As per the readme, you probably want something like this:

```ruby
one_week_from_now = Time.now + (60 * 60 * 24 * 7)

Omniboard::Column.new "Due soon" do
  conditions{ |p| p.active? && p.due && p.due <= one_week_from_now }
  group_by{ |p| p.due.to_date - Date.today }
end
```

Let me know if that helps!

**Comment by TurboTodd2k** [comment]
I pasted the code into a new column file and it erred as well...

At a bit of a loss, not enough of a programmer to debug this sadly, appreciate what you've built though...

I'm attaching the column file incase there's an obvious error.
[due.rb.zip](https://github.com/jyruzicka/omniboard/files/1564418/due.rb.zip)



/Users/Todd.Kidder/.omniboard/columns/config.rb:16:in `block (2 levels) in <top (required)>': undefined method `ancestry' for (1/1):Rational (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/column.rb:163:in `sort'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/column.rb:163:in `groups'
	from (erb):10:in `render_column'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/renderer.rb:29:in `render_column'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/renderer.rb:17:in `block in to_s'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/renderer.rb:17:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/lib/omniboard/renderer.rb:17:in `to_s'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:37:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:37:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/omniboard-1.2.1/bin/omniboard:37:in `<top (required)>'
	from /usr/local/bin/omniboard:23:in `load'
	from /usr/local/bin/omniboard:23:in `<main>'
Todd_Kidder:~ Todd.Kidder$

**Comment by jyruzicka** [comment]
Ah, I think I've found it. All the default columns group and sort projects based on their containing Omnifocus folder. These folders are represented as objects in the code, and have cool things like an `ancestry` method which provides a list of every containing folder up to the root of the document.

The "Due Soon" column groups projects based on how many days we have until they're due. If we pass a number to the default group naming/sorting function, when it's expecting an OmniFocus folder, it gets crotchety.

We should be able to fix the problem by adding some code to the "Due soon" column file, so it looks like this:

```ruby
one_week_from_now = Time.now + (60 * 60 * 24 * 7)

Omniboard::Column.new "Due soon" do
  conditions{ |p| p.active? && p.due && p.due <= one_week_from_now }

  # Our groups are e.g. 1, 2, 3, 4...
  group_by{ |p| p.due.to_date - Date.today }

  # Runs this block for each group, and sorts the results.
  # As 1 < 2 < 3 < 4 < ..., will sort in ascending order, most
  # urgent tasks first. To sort in descending order: sort_groups{ |i| -i }
  sort_groups{ |i| i }

  # Sets the name for each group.
  group_name{ |i| "Due in " + (i.to_i == 1 ? "1 day" : "#{i.to_i} days") }
end
```

I'll add some more code to the Readme for future users, and close the issue when (a) I get that uploaded, and (b) you can confirm that this fixes the problem on your end as well :).

**Comment by TurboTodd2k** [comment]
Excellent, this fixed it right up. One last trick I need to ask, would it be possible to assign colors to objects in the date groups? In my other columns I'm using the default folder grouping and have assigned colors, would love to have a way to assign those colors in the date sorted column.

Would it be doable with an ancestry look up?

I've attached a screen shot to illustrate.

Thank you for your help :-)

<img width="2592" alt="screen shot 2017-12-21 at 9 02 11 am" src="https://user-images.githubusercontent.com/22159610/34266445-fb8d9b10-e62d-11e7-8170-7d22f05dddb9.png">

**Comment by TurboTodd2k** [comment]
On an unrelated note, how do I figure out what properties are associate with |p| and |t| ?

**Comment by jyruzicka** [comment]
Unfortunately, omniboard doesn't support colouring individual projects at this stage. It'd be an interesting little project to allow individual project colours, but I don't see myself having the spare time to devote to improving omniboard in the near future. A good project if you want to learn ruby though :P

> On an unrelated note, how do I figure out what properties are associate with |p| and |t| ?

I should really make a proper API doc, but for the meantime, you can use this hack:

Let's say you want to know what methods you can play with in your `conditions` block for the standard "In Progress" column. Currently it might look something like this:

```ruby
Omniboard::Column.new "In Progress" do	
  conditions do |p|
    p.active? && !p.deferred?
  end
  ...
end
```

By adding the following code, you make ruby print out the object's methods and then quit:

```ruby
Omniboard::Column.new "In Progress" do
  conditions do |p|
    puts "p is a #{p.class}"
    puts (p.methods - Object.methods)
    exit 
    p.active? && !p.deferred?
  end
  ...
end
```

This won't tell you what each method *does*, but it will tell you which methods that variable `p` has right there, and better, it'll tell you what class `p` is. Then you can start rooting around in the source of omniboard, and see the code behind those methods.

**Comment by TurboTodd2k** [comment]
Thanks for the info and your help, have a good New Years!
