### ISSUE TITLE
how to create a column with flagged tasks only ?

### ISSUE THREAD

**Issue by tooh** [jyruzicka/omniboard#25]
Code I have now is

Omniboard::Column.new "Flagged" do
  conditions do |t| t.flagged?
  end

end

But this only shows flagged tasks if the the project is flagged.

I want only the flagged tasks to appear without flagging the whole project

**Comment by jyruzicka** [comment]
Hi @tooh,

Omniboard only shows projects, not tasks, in the main view. If you want to show any project that either:

* is flagged, or
* contains a flagged task

you should be able to use the code:

```ruby
Omniboard::Column.new "Flagged" do
  conditions do |p|
    p.flagged? or p.tasks.any?{ |t| t.flagged? }
  end
end
```
