### ISSUE TITLE
Question: Context Hierarchy Query

### ISSUE THREAD

**Issue by thecontinium** [jyruzicka/omniboard#27]
Hi 

I have a context hierarchy for "waiting for" tasks. e.g. wf:post:home

Is there a way to get to the "root" context which in my case is "wf" ?

In the example above can I find out if when I have a task that has a context name "home" whether it has a root "wf" ? 

cheers

**Comment by jyruzicka** [comment]
You can access the context hierarchy using the `ancestry` method. See the default `group_name` method for columns as an example of how to use it.
