### ISSUE TITLE
Update for omnifocus 3?

### ISSUE THREAD

**Issue by shenzo1** [jyruzicka/omniboard#28]
Hello,

I have been using omniboard for almost 2 years and reaped great benefits from your program.

Recently I have upgraded to OF3 and it seems omniboard can fetch the database from before the update but can't retrieve the modifications I have made after the update. Are you planning on an update for OF3?

Thanks for a great program!
Best,
S

**Comment by jyruzicka** [comment]
Hi there! Unfortunately I haven't touched this project since the OF3 upgrade. I suspect the issue will be the location of the library, which has changed from `~/Library/Containers/com.omnigroup.omnifocus2` to `~/Library/Containers/com.omnigroup.omnifocus3`.

**Comment by shenzo1** [comment]
That would make sense! So I suppose this has to be edited in rubyfocus? My programming skills are non-existent...

**Comment by shenzo1** [comment]
Made changes in local-fetcher, rebuilt and reinstalled and it is working! Thanks so much!

**Comment by jyruzicka** [comment]
No problem. Seems like your programming skills aren't so non-existent after all :P
