### ISSUE TITLE
Undefined method 'update'

### ISSUE THREAD

**Issue by meerestier** [jyruzicka/omniboard#5]
omniboard-0.3.3/lib/omniboard/omniboard.rb:102:in `update_document': undefined method `update' for false:FalseClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/omniboard-0.3.3/bin/omniboard:28:in <top (required)>
	from /usr/local/bin/omniboard:23:in load
	from /usr/local/bin/omniboard:23:in \<main\>

When I run omniboard… Any ideas?

**Comment by jyruzicka** [comment]
That's a strange one - looks like, for whatever reason, Omniboard isn't loading your Omnifocus document correctly. Might be a result of my recent update of the Rubyfocus code.

Try running `omniboard` with the `--reset` flag - that should get Omniboard to load everything from source again.

**Comment by jyruzicka** [comment]
Hello! Did resetting your Omniboard database fix the problem?

**Comment by meerestier** [comment]
Yes it did… Thanks!

**Comment by jyruzicka** [comment]
Glad to hear! 👍
